<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Employee extends Model
{
    use HasFactory;

    protected $table = 'EMPLOYEE';

    protected $fillable = [
        'COY_ID',
        'WKGP_CODE',
        'POS_CODE',
        'FIRST_NAME',
        'MIDDLE_NAME',
        'LAST_NAME',
        'FULL_NAME',
        'ROLE_CODE',
        'HOST_SINE_IN',
        'BR_CODE',
        'NAME_TYPE',
        'PHONE_NO',
        'MOBILE_NO',
        'EMAIL',
        'LOC_NO',
        'ADDRESS',
        'STREET_DESCR',
        'CITY_CODE',
        'ZIP_CODE',
        'PICTURE',
        'SIGNATURE',
        'STATUS',
        'ADMIN_FLAG',
        'HIRE_DATE',
        'QUIT_DATE',
        'LOGIN_ID',
        'PASSWORD',
        'PASSWORD_HINT',
        'HINT_ANSWER',
        'NET_FARE_ACCESS',
        'NATIONALITY_1',
        'SALES_TYPE',
        'ACCEPT_CASH',
        'ACCEPT_CREDIT',
        'ACCEPT_CHARGE',
        'ACCEPT_UATP',
        'ACCEPT_MIX',
        'ACCEPT_PDC',
        'PDC_DAYS',
        'PDC_BANK',
        'PDC_LIMIT',
        'PDC_BANK_ADDRESS',
        'NSF_LIMIT',
        'DAYS_DUE',
        'CREDIT_TERM',
        'CREDIT_LIMIT',
        'ISSUE_SOA',
        'LAST_ACTIVITY',
        'DEPT_CODE',
        'OVERRIDE_LIMIT',
        'SEL',
        'QUIT_REASON',
        'FAX_NO',
        'CATEGORY',
        'REMARKS',
        'TRAVEL_POLICY',
        'CASH_CUSTODIAN',
        'PCASH_ACCOUNT',
        'RFUND_ACCOUNT',
        'SOA_PERIOD',
        'GENERATE_SOA',
        'ACCOUNT_CODE',
        'TAX_EXEMPT',
        'COMM_FLAG',
        'COMM_RATE',
        'COMM_AMOUNT',
        'DISC_FLAG',
        'DISC_RATE',
        'DISC_AMOUNT',
        'CRT_BY',
        'CRT_DATE',
        'REV_BY',
        'REV_DATE',
        'ACCESS_STATUS',
        'NAME_CODE',
        'CTRY_CODE',
        'TIN',
        'TAX_ID_NO',
    ];
}
