<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Supplier extends Model
{
    use HasFactory;

    protected $table = 'SUPPLIER';

    protected $fillable = [
      'SUPP_ID',
      'SUPP_NAME',
      'SUPP_CODE',
      'OPEN_DATE',
      'CLOSE_DATE',
      'STATUS',
      'CLT_FLAG',
      'PHONE_NO_1',
      'PHONE_NO_2',
      'PHONE_NO_3',
      'FAX_NO_1',
      'FAX_NO_2',
      'FAX_NO_3',
      'EMAIL',
      'WEBSITE',
      'SALES_AGENT_AR',
      'SALES_AGENT_AP',
      'CATEGORY',
      'CREDIT_TERM_AR',
      'CREDIT_TERM_AP',
      'SALES_TYPE',
      'TAX_EXEMPT',
      'CREDIT_LIMIT_AR',
      'CREDIT_LIMIT_AP',
      'DAYS_DUE_AR',
      'DAYS_DUE_AP',
      'MAIL_ADDRESS',
      'MAIL_STREET',
      'MAIL_CITY_CODE',
      'MAIL_CTRY_CODE',
      'MAIL_ZIP_CODE',
      'BILL_ADDRESS',
      'BILL_STREET',
      'BILL_CITY_CODE',
      'BILL_CTRY_CODE',
      'BILL_ZIP_CODE',
      'DLVRY_ADDRESS',
      'DLVRY_STREET',
      'DLVRY_CITY_CODE',
      'DLVRY_CTRY_CODE',
      'DLVRY_ZIP_CODE',
      'HOME_LOC_FLAG',
      'OFC_LOC_FLAG',
      'TRAVEL_POLICY',
      'REMARKS',
      'CRT_BY',
      'CRT_DATE',
      'REV_BY',
      'REV_DATE',
      'SUPP_TYPE',
      'AL_CODE',
      'NAME_TYPE',
      'AL_ROUTE_1',
      'AL_ROUTE_2',
      'AL_ROUTE_3',
      'AL_ROUTE_4',
      'IATA_FLAG',
      'COMM_RATE',
      'COMM_AMOUNT',
      'AR_COMM_FLAG',
      'AR_COMM_RATE',
      'AR_COMM_AMOUNT',
      'AR_DISC_FLAG',
      'AR_DISC_RATE',
      'AR_DISC_AMOUNT',
      'ACCEPT_CASH',
      'ACCEPT_CHARGE',
      'ACCEPT_CREDIT',
      'ACCEPT_UATP',
      'ACCOUNT_CODE',
      'GENERATE_SOA',
      'SOA_PERIOD',
      'PDC_FLAG',
      'PDC_BANK',
      'PDC_DAYS',
      'PDC_ADDRESS',
      'NAME_CODE',
      'TIN',
      'TAX_ID_NO',
      'PAYMENT_TYPE',
      'WITH_POINT',
      'POINT_VALUE',
    ];
}
